name: GitHub Actions Demo

on:
  push:
    branches:
      - main  

jobs:
  demo-job:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run a Shell Command
        run: echo "Hello, GitHub Actions! harsha"
